### ISSUE TITLE
Any FOS Software for sharing DJ mixes?

### ISSUE THREAD

**Issue by TwizzyDizzy** [Kickball/awesome-selfhosted#1112]
Hi folks,

I've searched my ass off to find something that enables me to simply share some of my mixes. From the UI I would expect something soundcloud- or mixcloud-like, preferrably HTML5 based.

I can't seem to find ANYTHING the comes close to a modern UI.

This is probably not the place to ask, but I'd be immensely thankful for any hint someone might have :)

Cheers
Thomas

**Comment by nodiscc** [comment]
You could host your tracks on one of these https://github.com/Kickball/awesome-selfhosted#audio-streaming and make them publicly available (disable authentication). Otherwise a CMS/blogging engine that supports audio attachments could work.

I think asking on https://www.reddit.com/r/selfhosted/ would give you more options to explore

**Comment by TwizzyDizzy** [comment]
Yeah, checked the former already, not really viable. But you're right, /r/selfhosted would be a better place to ask. Closing.

Cheers & Thanks
Thomas
