### ISSUE TITLE
List indentation is inconsistent

### ISSUE THREAD

**Issue by quinncomendant** [Kickball/awesome-selfhosted#1201]
Currently, the indentation level of lists in README.md is inconsistent, e.g.:

<img width="145" alt="screen shot 2017-10-04 at 12 45 18" src="https://user-images.githubusercontent.com/6884276/31163834-f55fb656-a901-11e7-9a06-694b1945cf0c.png">

This causes nesting of lists:

<img width="194" alt="screen shot 2017-10-04 at 12 50 07" src="https://user-images.githubusercontent.com/6884276/31163965-a2987272-a902-11e7-9104-10d1ce5e6010.png">

Github (Markdown) doesn't require indentation to make a list. I propose we remove all the spaces before lists. It would reduce these errors if people didn't have to guess how many spaces are used.

(We can also use this opportunity to switch to using a hyphen `-` instead of asterisk `*`, but this is just a personal preference (one less keypress required on EN keyboard layouts).)

**Comment by quinncomendant** [comment]
And/or we can update the `test.js` rule to ensure list indentation is consistent. Currently it allows 0-4 space characters:

    const nodnospatt = /^ {0,4}\* \[.*?\]\(.*?\) - .{0,249}?\. `.*?` `.*?`/; // Regex for entries with no demo and no source code

**Comment by nodiscc** [comment]
I agree with the idea of making the indentation consistent. However some items (like Moped/Mopidy-Musicbox/Mopidy-party in your attached screenshot) are indented on a lower level _on purpose_ (because they require the top-level item to work, are just addons/modifications/3rd party UIs...).

There are a few other instances of this (Mumblecop, Matrix Web Console/Riot...)

 - [ ] The Firefox Content and Sync server (https://github.com/Kickball/awesome-selfhosted#bookmarks--link-sharing) used to be sub-items of the Auth Server. I don't know when this was removed, but it should be restored.
 - [ ] In the first time setting the top-level indentation level to 0 spaces would be good.
 - [ ] Updating `test.js` to enforce this: we could allow only 0 (top-level) and 3 spaces (sub-items).
 - Changing asterisk to hyphen can be done at a later stage, but I see your point about less key presses.

**Comment by quinncomendant** [comment]
Ok, I didn't notice indentation indicating software dependents, but that makes sense in hindsight.

Top-level 0 spaces will still solve most of the problem.

Sub-level should be 2 spaces, no?

**Comment by nodiscc** [comment]
> Sub-level should be 2 spaces, no?

Indeed

**Comment by nodiscc** [comment]
As discussed in #1269, I suggest the following approach:

* Pick a section you want to fix
* Clean the indentation in this single section, and fix any danger warnings about duplicate/broken links in the same time.
* When you've done the amount of changes you are comfortable with, send a PR. _The tests should pass._

**Comment by nodiscc** [comment]
Fixed thanks to @meitar .
