### ISSUE TITLE
Re-add Scrumblr

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#1423]
Scrumblr was mistakenly removed in #1408 and needs to be re-added.

**Comment by nodiscc** [comment]
I don't think it was removed: https://github.com/Kickball/awesome-selfhosted#task-managementto-do-lists

**Comment by Kickball** [comment]
Hmmmm, it does look like it is still there.

Not sure what happened to cause this but closing the issue.

**Comment by DJCrashdummy** [comment]
no, "it" got removed and is still missing! ...since "it" is about the Demo link for scrumblr as it is correct stated at #1408's renamed title. - i guess the demo-part of this issue got lost somewhere... :wink: 

added it again (a "quasi-duplicate" of #1407), hopefully correct and without further confusion: #1427
