### ISSUE TITLE
Apache Bloodhound has been discontinued since 2014

### ISSUE THREAD

**Issue by JC5** [Kickball/awesome-selfhosted#1636]
I'm not sure how it made the list in the first place because it was already discontinued in 2015. But perhaps it's time to remove it?

**Comment by evaryont** [comment]
I don't deny it's been very long since it's last update. But do we know if it's actually been "discontinued" or is it simply "feature complete"?

That being said, it's most likely actually discontinued. The bug tracker space has evolved considerably since 2014, and if a piece of software hasn't kept up with trends it likely isn't being actually used. And of course, there's likely unmanaged bitrot.

**Comment by JC5** [comment]
I agree. And let’s not forget five years of unmanaged security issues, if only in the libraries and tools it requires for use.
