### ISSUE TITLE
Add Tasks

### ISSUE THREAD

**Issue by m1guelpiedrafita** [Kickball/awesome-selfhosted#839]
[https://github.com/m1guelpiedrafita/Tasks](https://github.com/m1guelpiedrafita/Tasks).
[Demo](https://demo.miguelpiedrafita.com/tasks).
`PHP`

**Comment by greggluhring** [comment]
Get me off this list!!  I followed all the rules! I'm still on. I'm going 
to reply all until you remove me. Sorry everyone.


----------
On November 6, 2016 7:01:27 PM Edward D <notifications@github.com> wrote:

Closed #839 via 88620380b3606a8bd47ec2ce8d8b53f515ebf894.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/issues/839#event-849265075

**Comment by Kickball** [comment]
@greggluhring can you explain what is happening to you? Are you getting notifications for anything that happens in this project?

If so you can fix that by going to the [home page](https://github.com/Kickball/awesome-selfhosted) and change your watching status (in the top right).
