### ISSUE TITLE
AUTHORS file out of date

### ISSUE THREAD

**Issue by n8225** [Kickball/awesome-selfhosted#888]
@Kickball @nodiscc @AndyR207 
The current AUTHORS file hasn't been updated since September 28th.  Additionally some of the contributors show up multiple times with different emails and it looks like it includes merges.  Should we link directly to https://github.com/Kickball/awesome-selfhosted/graphs/contributors or should we use the api to create a list similar to the following:

Commits | Author
--- | ---
195| [nodiscc](https://github.com/nodiscc)
113| [Kickball](https://github.com/Kickball)
81| [n8225](https://github.com/n8225)
35| [Kovah](https://github.com/Kovah)
17| [AndyR207](https://github.com/AndyR207)
16| [jungle-boogie](https://github.com/jungle-boogie)
14| [cavebeat](https://github.com/cavebeat)
14| [m1guelpf](https://github.com/m1guelpf)
14| [n1trux](https://github.com/n1trux)
12| [Pe46dro](https://github.com/Pe46dro)

**Comment by m1guelpf** [comment]
List contributors using the Github API:
https://developer.github.com/v3/repos/#list-contributors

**Comment by Kickball** [comment]
The AUTHORS file was updated in #890.

We should, however, look towards a more long-term, automated solution such as integration into the website @AndyR207 is developing.

**Comment by m1guelpf** [comment]
@Kickball You could setup a git hook

**Comment by nodiscc** [comment]
The new AUTHORS.md file added in https://github.com/Kickball/awesome-selfhosted/pull/890 doesn't seem to list all contributors, only those with an associated Github account. (103 additions, 205 deletions...)

I agree about setting up a git hook to auto-update the authors file, but let's use `git shortlog -sne` since the data from Github API returns incorrect information about the contributors.

Our toolchain should stay portable and not depend on a third-party API when possible.

**Comment by n8225** [comment]
I'll build a new one use git shortlog in the next day or two
