### ISSUE TITLE
How about a top 10 mini-list?

### ISSUE THREAD

**Issue by AdityaAnand1** [Kickball/awesome-selfhosted#894]
This is an excellent resource for people who are looking for something specific like a password manager or cloud storage or something. But for those who are just browsing (like me), it's a bit overwhelming. I don't know where to start.

I propose adding a small list of the 10 or so most popular self hosted solutions, stuff that everyone could instantly relate to and jump right into the world of self hosting. We could figure out which ones are popular by figuring out how widely used the service/web apps are, how active their repos are etc.

What do you think?

**Comment by m1guelpf** [comment]
@AdityaAnand1 I like the idea!

**Comment by nodiscc** [comment]
> But for those who are just browsing (like me), it's a bit overwhelming. I don't know where to start.

Well it depends on what you're trying to achieve? If you could tell us more about what kind of setup you want, what are your goals, etc it would be easier to provide an answer.

> I propose adding a small list of the 10 or so most popular self hosted solutions, stuff that everyone could instantly relate to and jump right into the world of self hosting. 

Personally I am against adding a "top" list because the criteria for "top" are _very_ subjective. How do we define popular? Github stars? They can be manipulated, and what about projects that are not on github? Projects that are easy to setup? Active development? What about mature projects that don't need heavy development? Etc etc

Many projects listed here are excellent quality software and a "top 10" can not list them all. Let's keep this list an unbiased, comprehensive list.

There are many good places to ask "where do I start" (https://www.reddit.com/r/selfhosted comes to mind, or come say hi at https://chat.awesome-selfhosted.com/). And many blog posts with lists of great self hosted services. Look at the https://github.com/Kickball/awesome-selfhosted#self-hosting-solutions for an easy start. (I also have my own setup which I built from scratch, you can find it on my Github profile page - It's rather easy to understand and testers are welcome)

Or maybe there's room for a side project/guide on how to setup your first self-hosted environment? Anyway if you're "just browsing", just pick software in the list and try it for yourself. If you have a particular need and don't know where to start, ask away.

**Comment by nodiscc** [comment]
Closing since there has been no feedback for a week.
