### ISSUE TITLE
Add Scrumblr

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#896]
https://github.com/aliasaria/scrumblr
Collaborative Online Scrum Tool Using Websockets, Node.js, jQuery, and CSS3 http://scrumblr.ca
Node.js
GPLv3

**Comment by greggluhring** [comment]
Yes that's right I said will you please remove me and you ignored me remove 
me please


On December 16, 2016 8:14:26 AM nodiscc <notifications@github.com> wrote:

https://github.com/aliasaria/scrumblr
Collaborative Online Scrum Tool Using Websockets, Node.js, jQuery, and CSS3 
http://scrumblr.ca
Node.js
GPLv3

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/issues/896

**Comment by greggluhring** [comment]
I know this probably only two more people on this list so it's not going to 
matter but I'd still like to get the f*** off


On December 16, 2016 8:14:26 AM nodiscc <notifications@github.com> wrote:

https://github.com/aliasaria/scrumblr
Collaborative Online Scrum Tool Using Websockets, Node.js, jQuery, and CSS3 
http://scrumblr.ca
Node.js
GPLv3

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/issues/896

**Comment by nodiscc** [comment]
@greggluhring I've removed your comments because you were spamming. You have to manage your subcriptions yourself, see my answer at https://github.com/Kickball/awesome-selfhosted/issues/427#issuecomment-267762492

**Comment by n8225** [comment]
Merged #903
