### ISSUE TITLE
Add Textpad

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#897]
https://github.com/novavex/textpad
 savepad, based on notepad.cc
PHP
MIT

**Comment by greggluhring** [comment]
Remove me please remove me please sir remove me all of you people someone 
must know there must be a easy way remove me


On December 16, 2016 9:29:22 AM nodiscc <notifications@github.com> wrote:

https://github.com/novavex/textpad
 savepad, based on notepad.cc
PHP
MIT

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/issues/897

**Comment by n8225** [comment]
Merged #902
