### ISSUE TITLE
Add QOwnNotes

### ISSUE THREAD

**Issue by dxerw** [Kickball/awesome-selfhosted#973]
QOwnNotes (https://github.com/pbek/QOwnNotes) - QOwnNotes is the open source notepad with markdown support and todo list manager for GNU/Linux, Mac OS X and Windows, that works together with the default notes application of ownCloud.

**Comment by nodiscc** [comment]
http://www.qownnotes.org/
This is a desktop application.

**Comment by jeremyfritzen** [comment]
Hi!

Sorry it's been a long time since the last comment.

Indeed QownNotes is a desktop application. But you can syncrhonize your notes natively with Nextcloud. So this software meets the same needs as other software listed in the note-taking category.

I suppose people looking in this repo for a self-hosted note-taking app would like to see QOwnNotes.

What do you think?

**Comment by nodiscc** [comment]
I can synchronize Excel spreadsheets with Nextcloud, doesn't make Excel a good candidate for the list.

In this specific case, since it has native integration with Nextcloud, a solution would be adding a `[Clients]` link to the Nextcloud entry, and point it to a page listing Nextcloud clients and related software. You could list QOwnNotes there. I found https://github.com/andreasjacobsen93/awesome-nextcloud but it is no longer maintained. If you are willing to maintain such a page/list we could link to it.
